# Uncomment the next line to define a global platform for your project

platform :ios, '12.0'

inhibit_all_warnings!

target 'LJL' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'AMap3DMap'
  pod 'AMapSearch'
  pod 'AMapLocation'
  
  pod 'Realm', '3.13.1'
  
  pod 'Masonry', '1.1.0'
  
  pod 'SnapKit', '4.2.0'
  
  pod 'PKHUD', '5.2.1'

end
